### ISSUE TITLE
TimeFormat Issue

### ISSUE THREAD

**Issue by rgn** [themouette/jquery-week-calendar#13]
If you set 'H:m' as timeFormat in the full_demo example, time will not be displayed correct. It`s allways 10 past full hour.

I`ve take screenshots, first is with default time format, second with H:m set.

http://img217.imageshack.us/i/correctd.png/
http://img844.imageshack.us/i/bugyi.png/

**Comment by andrzej-aa** [comment]
Lol, dude.Because of you I spent my free time on updating a function responsible for formating time just to find out that you made a mistake. Look here: http://jacwright.com/projects/javascript/date_format and here: http://php.net/manual/en/function.date.php And what do we see? m=month. Funny, right? Right. Issue solved. Bye :)

**Comment by themouette** [comment]
so I close this ticket :)
