### ISSUE TITLE
Bug in demo_3

### ISSUE THREAD

**Issue by zjean** [themouette/jquery-week-calendar#16]
Hi,

I found a bug in the calendar with multiple users. If you open weekcalender_demo_3 (http://themouette.github.com/jquery-week-calendar/weekcalendar_demo_3.html) and create an event.
Now move that event to another date/time and you wil see that the old timespan will remain busy, instead of becoming free.

**Comment by zjean** [comment]
I found another bug in this demo_3: when you create an event outside a busy timespan, and drop into the busy timespan you do not get an error message.

**Comment by themouette** [comment]
Hi,

According to me this is not a buggy behavior, it is mostly to show a basic implementation of te calendar with free busy.

You should never rely on client side logic for security, that's why this part is not implemented on client side, it has to be done on server side.

If you feel like improving this behavior feel free.

Julien.

**Comment by zjean** [comment]
Hi,

thanks for your response. I would like to improve this behaviour, but are not so deep into jQuery to fix this. I simply don't know where to begin. I read throught the source code, but don't see the place to fix this.
