### ISSUE TITLE
Fast Switching of Weeks Causes Ajax Error

### ISSUE THREAD

**Issue by markjlorenz** [themouette/jquery-week-calendar#34]
Using Safari, Chrome or Firefox (not sure about IE), with an ajax data source for the calendar data, if the user presses the 'next' or 'previous' buttons in rapid succession an alert is shown saying "unable to get data, error:"

This is caused by `_currentAjaxCall.abort();`  which fires the xhr objects error callback.

I recommend changing:
    error: function(XMLHttpRequest, textStatus, errorThrown){
        alert('unable to get data, error:' + textStatus);
    }

to look for the 'abort' error, and then ignoring it.
    error: function(XMLHttpRequest, textStatus, errorThrown){
        if(errorThrown != 'abort'){
            alert('unable to get data, error:' + textStatus);
        }
    }

Note that `errorThrown` and `textStatus` are just "error" with jQuery <= 1.4.4 and "abort" with jQuery 1.5.

As an aside:
I know jQuery 1.5 is brand-new, is weekCalendar compatible?

**Comment by dittodhole** [comment]
this one is driving our quality control insane :)
i ended with blockUI (http://jquery.malsup.com/block/): block the ui on load, unblock it when finished loading...
but to enhance this one, i will have to preload events and keep a cache, so that going prev and next won't cause a complete reload...

jQuery 1.5:
we use this version, and there are no problems with the actual release of weekCalendar. but there was a bug introduced when `.clone()` (or sth alike) was enhanced (jquery interna), so that jQuery 1.5 won't work with IE 9 RC :(

**Comment by themouette** [comment]
this is fixed for both 1.5 and 1.4
