### ISSUE TITLE
users array as function result.

### ISSUE THREAD

**Issue by pawelantczak** [themouette/jquery-week-calendar#46]
Hello.
Is there any possibility to improve code to allow users array to be generated from function?
Thanks in advance.

**Comment by themouette** [comment]
You can map your own user behavior to the calendar thanks to configuration callbacks.
mor information on the [wiki](https://github.com/themouette/jquery-week-calendar/wiki/Script-options) under user management paragraph

Julien

**Comment by pawelantczak** [comment]
Thanks, but what i'm talking about is according to yours tip: "Warning: it has to be a real Array".
I've made quick fix for this, similar to jsonOptions:
<code>_getUsers: function() {
        if ($.isFunction(this.options.users)) {
            return this.options.users();
        }
        if ($.isArray(this.options.users)) {
          return this.options.users;
        }
        return [];
      },</code>
and in _renderCalendarHeader:
<code>
options.users = self._getUsers();
</code>
From now on 'users' option can be actual array or function which will return an array.

**Comment by themouette** [comment]
that's an easy change, fork the repo, do it and send me a pull request.
I'm a bit busy with other projects right now :)

First solution is to change all the **options.users** calls (sometimes it is **o.users**) to the new **_getUser** function. You'l have to expose a *_getUser *_function too in order to access it.

A more efficient way can be to do it in the **_setOption** function as it is done only once.

If you need to re-parse the users every time you access it, first solution is better, but I guess that when your users changes you would also reload events, so second solution may be enough.

Cheers,

Julien.

**Comment by jamesvanleuvaan** [comment]
what about returning/receiving the user as a json string? I think it'll manage dynamic updates more easily

**Comment by themouette** [comment]
Hi,
users is a list, each user might be an object or whatever fits your needs, but the user list is an array...

Cheers

**Comment by jamesvanleuvaan** [comment]
thanx :) i'm enjoying the features with the calendar. I'm going to need your help for sure with the busy-free aspects
